[theme]
base                = "light"
primaryColor        = "#007aff"
backgroundColor     = "#f2f2f7"
secondaryBackground = "#ffffff"
textColor           = "#1c1c1e"
font                = "sans serif"